### ISSUE TITLE
Interest in moving to swaywm org?

### ISSUE THREAD

**Issue by ddevault** [drewt/chicken-wlroots#1]
Hiya! Just stopping by to ask if you have any interest in moving this project to the swaywm org, where most other wlroots wrapper libraries live. It would help people discover your library more easily - but you'd still retain your role and autonomy as maintainer.

**Comment by drewt** [comment]
Sure. What should I do to move the repo? Do I just transfer it to swaywm under the settings on Github?

**Comment by ddevault** [comment]
I invited you to the org - first, accept the invite, then transfer the repo, then I'll wire you up as the maintainer.

**Comment by drewt** [comment]
Done.

**Comment by ddevault** [comment]
Cheers :)
